---

- name: Kubernetes pre-requirements
  hosts: k8s

  tasks:

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux

    - name: Disable SWAP
      shell: swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
      register: swap

    - name: Add docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        file: docker_ce
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes


    - name: Add k8s repository
      yum_repository:
        name: Kubernetes
        description: k8s repo
        file: kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
        enabled: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes


    - name: Install the latest version of Docker
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io 
#          - yum-plugin-versionlock
        state: latest
        allowerasing: yes

    - name: Rebooting {{ hostname }}
      reboot:
        test_command: uptime
      when: selinux.changed or swap.changed

    - name: Enable & start service docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install k8s tools
      yum:
        name:
          - kubelet
          - kubeadm
          - kubectl 
        state: present


    - name: Creating a file with content
      copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
          br_netfilter


    - name: Creating a file with content
      copy:
        dest: "/etc/sysctl.d/k8s.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: Enable Kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: yes

    - name: Setup Docker daemon
      copy:
        dest: "/etc/docker/daemon.json"
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
            "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }


    - name: Reload the systemd config
      ansible.builtin.systemd:
        name: docker
        daemon_reload: yes
        state: reloaded

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: yes